### ISSUE TITLE
'Sd Fat Not declared'

### ISSUE THREAD

**Issue by Thman558** [spacehuhn/ArduinoPcap#12]
In function 'void sniffer(uint8_t*, uint16_t)':
esp8266_pcap_serial:39:28: error: 'now' was not declared in this scope
   uint32_t timestamp = now(); //current timestamp 
                            ^
exit status 1
'SdFat' has not been declared

**Comment by CsomagoltWifi** [comment]
"If you don't use an ESP32, you will need the [SdFat](https://github.com/greiman/SdFat) library."
Have you install it correctly?

**Comment by 0rbianta** [comment]
It only works with SdFat v2.0.1
