### ISSUE TITLE
Compilation error I do not understand.

### ISSUE THREAD

**Issue by lstowoda** [spacehuhn/ArduinoPcap#17]
In file included from C:\Users\luk\Documents\Arduino\libraries\ArduinoPcap-master\src/PCAP.h:18:0,
                 from C:\Users\luk\AppData\Local\Temp\.arduinoIDE-unsaved2023829-7704-1mpxzmh.l8j3\esp8266_pcap_serial\esp8266_pcap_serial.ino:17:
C:\Users\luk\Documents\Arduino\libraries\SdFat\src/SdFat.h:462:16: error: 'typedef class FsFile File' conflicts with a previous declaration
 typedef FsFile File;
                ^
In file included from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/CertStoreBearSSL.h:26:0,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:30,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/WiFiClientSecure.h:41,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,
                 from C:\Users\luk\AppData\Local\Temp\.arduinoIDE-unsaved2023829-7704-1mpxzmh.l8j3\esp8266_pcap_serial\esp8266_pcap_serial.ino:14:
C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266/FS.h:52:7: note: previous declaration 'class fs::File'
 class File : public Stream
       ^
In file included from C:\Users\luk\Documents\Arduino\libraries\ArduinoPcap-master\src/PCAP.h:18:0,
                 from C:\Users\luk\AppData\Local\Temp\.arduinoIDE-unsaved2023829-7704-1mpxzmh.l8j3\esp8266_pcap_serial\esp8266_pcap_serial.ino:17:
C:\Users\luk\Documents\Arduino\libraries\SdFat\src/SdFat.h:462:16: error: 'typedef class FsFile File' conflicts with a previous declaration
 typedef FsFile File;
                ^
In file included from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/CertStoreBearSSL.h:26:0,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:30,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/WiFiClientSecure.h:41,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,
                 from C:\Users\luk\AppData\Local\Temp\.arduinoIDE-unsaved2023829-7704-1mpxzmh.l8j3\esp8266_pcap_serial\esp8266_pcap_serial.ino:14:
C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266/FS.h:52:7: note: previous declaration 'class fs::File'
 class File : public Stream
       ^
In file included from C:\Users\luk\Documents\Arduino\libraries\ArduinoPcap-master\src/PCAP.h:18:0,
                 from C:\Users\luk\AppData\Local\Temp\.arduinoIDE-unsaved2023829-7704-1mpxzmh.l8j3\esp8266_pcap_serial\esp8266_pcap_serial.ino:17:
C:\Users\luk\Documents\Arduino\libraries\SdFat\src/SdFat.h:462:16: error: 'typedef class FsFile File' conflicts with a previous declaration
 typedef FsFile File;
                ^
In file included from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/CertStoreBearSSL.h:26:0,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:30,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/WiFiClientSecure.h:41,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,
                 from C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,
                 from C:\Users\luk\AppData\Local\Temp\.arduinoIDE-unsaved2023829-7704-1mpxzmh.l8j3\esp8266_pcap_serial\esp8266_pcap_serial.ino:14:
C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\cores\esp8266/FS.h:52:7: note: previous declaration 'class fs::File'
 class File : public Stream
       ^
Mehrere Bibliotheken wurden für "SdFat.h" gefunden
  Benutzt: C:\Users\luk\Documents\Arduino\libraries\SdFat
  Nicht benutzt: C:\Users\luk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266SdFat
exit status 1

Compilation error: exit status 1

**Comment by 0rbianta** [comment]
It only works with SdFat v2.0.1
